/* Auto-generated by genmsg_cpp for file /home/abhishek/ros_workspace/abhishek/P3DX_sbpl/msg/sbpl_msg.msg */
#ifndef P3DX_SBPL_MESSAGE_SBPL_MSG_H
#define P3DX_SBPL_MESSAGE_SBPL_MSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace P3DX_sbpl
{
template <class ContainerAllocator>
struct sbpl_msg_ {
  typedef sbpl_msg_<ContainerAllocator> Type;

  sbpl_msg_()
  : sbpl_wait_flag(false)
  , sbpl_present_x(0)
  , sbpl_present_y(0)
  , sbpl_new_x(0)
  , sbpl_new_y(0)
  , start_P3DX_motion(false)
  {
  }

  sbpl_msg_(const ContainerAllocator& _alloc)
  : sbpl_wait_flag(false)
  , sbpl_present_x(0)
  , sbpl_present_y(0)
  , sbpl_new_x(0)
  , sbpl_new_y(0)
  , start_P3DX_motion(false)
  {
  }

  typedef uint8_t _sbpl_wait_flag_type;
  uint8_t sbpl_wait_flag;

  typedef int8_t _sbpl_present_x_type;
  int8_t sbpl_present_x;

  typedef int8_t _sbpl_present_y_type;
  int8_t sbpl_present_y;

  typedef int8_t _sbpl_new_x_type;
  int8_t sbpl_new_x;

  typedef int8_t _sbpl_new_y_type;
  int8_t sbpl_new_y;

  typedef uint8_t _start_P3DX_motion_type;
  uint8_t start_P3DX_motion;


private:
  static const char* __s_getDataType_() { return "P3DX_sbpl/sbpl_msg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "c5e98ef0a5b021e3e77f5108ba25b386"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool sbpl_wait_flag\n\
int8 sbpl_present_x\n\
int8 sbpl_present_y\n\
int8 sbpl_new_x\n\
int8 sbpl_new_y\n\
bool start_P3DX_motion\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, sbpl_wait_flag);
    ros::serialization::serialize(stream, sbpl_present_x);
    ros::serialization::serialize(stream, sbpl_present_y);
    ros::serialization::serialize(stream, sbpl_new_x);
    ros::serialization::serialize(stream, sbpl_new_y);
    ros::serialization::serialize(stream, start_P3DX_motion);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, sbpl_wait_flag);
    ros::serialization::deserialize(stream, sbpl_present_x);
    ros::serialization::deserialize(stream, sbpl_present_y);
    ros::serialization::deserialize(stream, sbpl_new_x);
    ros::serialization::deserialize(stream, sbpl_new_y);
    ros::serialization::deserialize(stream, start_P3DX_motion);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(sbpl_wait_flag);
    size += ros::serialization::serializationLength(sbpl_present_x);
    size += ros::serialization::serializationLength(sbpl_present_y);
    size += ros::serialization::serializationLength(sbpl_new_x);
    size += ros::serialization::serializationLength(sbpl_new_y);
    size += ros::serialization::serializationLength(start_P3DX_motion);
    return size;
  }

  typedef boost::shared_ptr< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct sbpl_msg
typedef  ::P3DX_sbpl::sbpl_msg_<std::allocator<void> > sbpl_msg;

typedef boost::shared_ptr< ::P3DX_sbpl::sbpl_msg> sbpl_msgPtr;
typedef boost::shared_ptr< ::P3DX_sbpl::sbpl_msg const> sbpl_msgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace P3DX_sbpl

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5e98ef0a5b021e3e77f5108ba25b386";
  }

  static const char* value(const  ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc5e98ef0a5b021e3ULL;
  static const uint64_t static_value2 = 0xe77f5108ba25b386ULL;
};

template<class ContainerAllocator>
struct DataType< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "P3DX_sbpl/sbpl_msg";
  }

  static const char* value(const  ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool sbpl_wait_flag\n\
int8 sbpl_present_x\n\
int8 sbpl_present_y\n\
int8 sbpl_new_x\n\
int8 sbpl_new_y\n\
bool start_P3DX_motion\n\
\n\
";
  }

  static const char* value(const  ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.sbpl_wait_flag);
    stream.next(m.sbpl_present_x);
    stream.next(m.sbpl_present_y);
    stream.next(m.sbpl_new_x);
    stream.next(m.sbpl_new_y);
    stream.next(m.start_P3DX_motion);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct sbpl_msg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::P3DX_sbpl::sbpl_msg_<ContainerAllocator> & v) 
  {
    s << indent << "sbpl_wait_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sbpl_wait_flag);
    s << indent << "sbpl_present_x: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sbpl_present_x);
    s << indent << "sbpl_present_y: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sbpl_present_y);
    s << indent << "sbpl_new_x: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sbpl_new_x);
    s << indent << "sbpl_new_y: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sbpl_new_y);
    s << indent << "start_P3DX_motion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_P3DX_motion);
  }
};


} // namespace message_operations
} // namespace ros

#endif // P3DX_SBPL_MESSAGE_SBPL_MSG_H

